# Generated by Django 4.2.3 on 2023-08-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Type',
            fields=[
                ('employee_type', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('charge_permonth', models.PositiveIntegerField()),
                ('other_details', models.TextField()),
            ],
        ),
    ]
