# Generated by Django 4.2.3 on 2023-08-12 09:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_type',
            name='charge_permonth',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=45)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('experience', models.CharField(max_length=20)),
                ('employee_pic', models.FileField(default='', upload_to='solution/employee_pic')),
                ('about_employee', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solution.employee_type')),
            ],
        ),
    ]
