# Generated by Django 4.2.3 on 2023-08-12 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(max_length=6)),
            ],
        ),
    ]
