# Generated by Django 4.2.3 on 2023-08-16 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0007_offers_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('rating', models.CharField(max_length=6)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='solution.user')),
            ],
        ),
    ]
